{% set name = "atmcirctools" %}
{% set version = "0.2.0" %}
{% set build = "0" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  git_rev: v{{ version }}
  git_url: git+ssh://git@git.iac.ethz.ch/atmcirc/tools/atmcirctools.git

build:
  noarch: python
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - cmake>=3.22.3
    - ninja>=1.10.2
    - numpy>=1.22.3
    - scikit-build>=0.14.1
    - setuptools>=35.0.2
    - wheel>=0.37.1
  run:
    - atmcirclib==0.2.3
    - gt4py==2022.04.09
    - pycg==0.0.5
    - click>=8.1
    - h5netcdf>=1.0
    - numpy>=1.22
    - pygraphviz>=1.9
    - xarray>=2022.3

test:
  imports:
    - {{ name }}

about:
  license: MIT
  summary: Compute gradient of PV on TH surfaces.
  description: |
    # DPV-TH: Compute gradient of PV on TH surfaces.
