{% set name = "atmcirctools" %}
{% set version = "0.3.0" %}
{% set build = "0" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  git_rev: v{{ version }}
  git_url: git+ssh://git@git.iac.ethz.ch/atmcirc/tools/atmcirctools.git

build:
  noarch: python
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools>=35.0.2
    - wheel>=0.37
  run:
    - atmcirclib==0.4.0
    - gt4py==2022.04.09
    - pycg==0.0.5
    - click>=8.1
    - numpy>=1.22
    - pygraphviz>=1.9
    - scikit-build>=0.14
    - toml>=0.10
    - xarray>=2022.3

test:
  imports:
    - {{ name }}

about:
  license: MIT
  summary: Useful tools by the Atmospheric Circulation group
  description: |
    # AtmCircTools: Useful tools by the Atmospheric Circulation group
