# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: ed797d1
_src_path: git@git.iac.ethz.ch:atmcirc/templates/python-project.git
author_email: stefan.ruedisuehli@env.ethz.ch
author_email_domain: env.ethz.ch
author_email_name: stefan.ruedisuehli
author_first_name: Stefan
author_full_name: Stefan Ruedisuehli
author_last_name: Ruedisuehli
git_url: https://git.iac.ethz.ch/atmcirc/tools/atmcirctools.git
git_url_org: atmcirc/tools
git_url_provider: https://git.iac.ethz.ch
git_user: atmcirc
project_description: Useful tools by the Atmospheric Circulation group
project_keywords: atmospheric science, modeling
project_long_name: AtmCircTools
project_package_name: atmcirctools
project_short_name: atmcirctools
project_url: https://git.iac.ethz.ch/atmcirc/tools/atmcirctools.git
project_version: 0.2.2
python_requires: '>=3.9'
python_version: '3.9'
